export rvm_bin_path=/usr/local/rvm/bin
export GEM_HOME=/usr/local/rvm/gems/ruby-2.2.0
export SHELL=/bin/bash
export NLS_LANG=AMERICAN_AMERICA.AL32UTF8
export IRBRC=/usr/local/rvm/rubies/ruby-2.2.0/.irbrc
export MY_RUBY_HOME=/usr/local/rvm/rubies/ruby-2.2.0
export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client/lib:
export rvm_path=/usr/local/rvm
export ORACLE_BASE=/usr/lib/oracle/11.2
export rvm_prefix=/usr/local
export PATH=/usr/local/rvm/gems/ruby-2.2.0/bin:/usr/local/rvm/gems/ruby-2.2.0@global/bin:/usr/local/rvm/rubies/ruby-2.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/rvm/bin
export rvm_version=1.26.11 
export GEM_PATH=/usr/local/rvm/gems/ruby-2.2.0:/usr/local/rvm/gems/ruby-2.2.0@global
export ORACLE_HOME=/usr/lib/oracle/11.2/client
export RUBY_VERSION=ruby-2.2.0
export _=/usr/bin/env
cd /home/istock
pumactl restart
